Create about.md
polympics/wiki pull request #10
Opened 2021-05-26 17:21 UTC by esparkhu

2021-05-26 18:15 UTC, Artemis21 commented
This seems largely to duplicate `index.md` (wiki home)?

2021-05-26 18:16 UTC, Artemis21 commented
Also you've used `*` for bullets in some places but `-` in others, harmless but why?

2021-05-26 21:20 UTC, esparkhu commented
Yes, It is pretty much the same as the wiki home. I don't know what else to put on the about page. Do we even need it? I'm open to suggestions.

I used - instead of bullets because I was copy/pasting from discord. It wasn't a conscious choice.

2021-06-07 20:50 UTC, Artemis21 requested changes
Just minor link formatting issues.

Edit: Looks like my review wasn't attached, will do another one.

2021-06-07 20:53 UTC, Artemis21 requested changes
As above.

2021-06-07 20:53 UTC, Artemis21 commented on content/about.md
> +Players register)https://polytopia.fun/login) and join a team based on nationality. Participants will need a discord account. Teams will send players to compete in ten different events. Some events a
```suggestion
Players [register](/login) and join a team based on nationality. Participants will need a discord account. Teams will send players to compete in ten different events. Some events allow multiple entries per team, others are limited to one representative (or pair of representatives) per team. See [event rules](/wiki/events) for more details. Some events are mobile only while others allow for Steam or mobile users.
```

2021-06-09 21:59 UTC, closed without merging