Create discord.md
polympics/wiki pull request #13
Opened 2021-05-26 17:36 UTC by esparkhu

2021-05-26 18:22 UTC, Artemis21 requested changes

2021-05-26 18:22 UTC, Artemis21 commented on content/discord.md
> +https://discord.gg/kJG7eM4hDG
```suggestion
## [Polympics Discord Server](https://discord.gg/kJG7eM4hDG)

The official home of the event. Join to start chatting with fellow participants and team members!
```

2021-05-26 18:22 UTC, Artemis21 commented on content/discord.md
> +https://discord.gg/kJG7eM4hDG
Note that there should never be more that one single-`#` on a page, Google will rank pages lower for it.

2021-05-26 18:22 UTC, Artemis21 commented on content/discord.md
> +https://discord.gg/polytopia
```suggestion
## [Official Polytopia Discord Server](https://discord.gg/polytopia)

The official Discord server for The Battle of Polytopia.
```

2021-05-26 18:22 UTC, Artemis21 commented on content/discord.md
> +To register for the event please [login](login)
```suggestion
To register for the event please [/login](login).
```
(Absolute URL is required.)

2021-05-26 21:17 UTC, esparkhu reviewed
Okay. thanks

How do I approve the changes? Or do I need to?

2021-05-26 21:17 UTC, esparkhu commented
Yes. Thanks.

2021-05-26 22:28 UTC, Artemis21 commented
There should be a "Commit suggestion" button?

2021-05-26 22:29 UTC, Artemis21 commented
> Yes. Thanks.

Was this meant to be in reply to something?

2021-06-07 20:51 UTC, Artemis21 approved these changes
Looks good

2021-06-07 20:51 UTC, merged